title: Setup Wireless Canon Printer on MAC  
description: Download canon printer driver software from Canon.com/ijsetup. Setup a wireless canon printer with your mac using the simple steps on this webpage.
theme: jekyll-theme-cayman
